-- Phase 5 · Landing pages generated by Developer Agent

create table if not exists landing_pages (
  id uuid primary key default gen_random_uuid(),
  client_id text not null,
  campaign_id uuid references campaigns(id) on delete set null,
  slug text not null,
  html text not null,
  published_url text,
  created_at timestamptz default now()
);

create unique index if not exists idx_landing_slug on landing_pages(client_id, slug);
